apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /linkding(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: app-service-linkding
                port:
                  number: 80
