apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

nameSuffix: -linkding

patches:
  - path: ./deployment.yaml
  - path: ./service.yaml
  - path: ./ingress.yaml
